apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-react-js
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: express-react-js
        image: express-react-js:latest
        workingDir: "/usr/app"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi