apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: express-react-js
  environment: test

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml

images:
- name: express-react-js
  newTag: 0.1.0-deploy-30
